### ISSUE TITLE
Windows环境下如何执行程序？

### ISSUE THREAD

**Issue by LondyGhost** [gngpp/qrcode-token#2]
![QQ截图20220320120251](https://user-images.githubusercontent.com/16317989/159147618-b68cbe8e-6b2c-44f7-9c50-118c2fca868c.png)
在cmd 和powershell里执行release的文件，都无法成功运行。

**Comment by 0x676e67** [comment]
截图来我看看

**Comment by 0x676e67** [comment]
![image](https://user-images.githubusercontent.com/51810656/159145659-12c2212d-3bc5-4cf3-b3dc-13a643dfe076.png)
你把解压下来的qrcode-token加一下.exe后缀在terminal就可以运行了，cmd不建议用会有乱码，打包出了点问题

**Comment by 0x676e67** [comment]
刚发了release，已经修复后缀了

**Comment by LondyGhost** [comment]
[https://s3.bmp.ovh/imgs/2022/03/f93a1fd1c5a49446.png](url)

**Comment by LondyGhost** [comment]
> 刚发了release，已经修复后缀了

我更新了release，但是执行后还是这种情况。已更新截图。系统已经安装了go 1.18

**Comment by 0x676e67** [comment]
说了不要用cmd，那个powershell也是一样的都是gbk编码，你去微软商店下个新版Windows terminal 那个支持utf8编码

**Comment by zf1976** [comment]
说了不要用cmd，那个powershell也是一样的都是gbk编码，你去微软商店下个新版Windows terminal 那个支持utf8编码

**Comment by zf1976** [comment]
> 说了不要用cmd，那个powershell也是一样的都是gbk编码，你去微软商店下个新版Windows terminal 那个支持utf8编码

https://pic2.zhimg.com/v2-2ed73e0d647ccddf80507bb0c092d051_b.jpg

**Comment by 0x676e67** [comment]
> > 刚发了release，已经修复后缀了
> 
> 我更新了release，但是执行后还是这种情况。已更新截图。系统已经安装了go 1.18

![v2-2ed73e0d647ccddf80507bb0c092d051_b.jpg](https://user-images.githubusercontent.com/51810656/159148567-a175111a-6e8c-490a-8215-e01a7d073273.jpg)

**Comment by LondyGhost** [comment]
> > > 刚发了release，已经修复后缀了
> > 
> > 
> > 我更新了release，但是执行后还是这种情况。已更新截图。系统已经安装了go 1.18
> 
> ![v2-2ed73e0d647ccddf80507bb0c092d051_b.jpg](https://user-images.githubusercontent.com/51810656/159148567-a175111a-6e8c-490a-8215-e01a7d073273.jpg)

谢谢。已经成功运行。软件是否能增加一个功能。将返回的token值直接echo到文本文件，或者读取。这样可以与github上的aliyunpan-cli项目配合实现命令行环境上传下载文件。

**Comment by 0x676e67** [comment]
> > > > 刚发了release，已经修复后缀了
> > > 
> > > 
> > > 我更新了release，但是执行后还是这种情况。已更新截图。系统已经安装了go 1.18
> > 
> > ![v2-2ed73e0d647ccddf80507bb0c092d051_b.jpg](https://user-images.githubusercontent.com/51810656/159148567-a175111a-6e8c-490a-8215-e01a7d073273.jpg)
> 
> 谢谢。已经成功运行。软件是否能增加一个功能。将返回的token值直接echo到文本文件，或者读取。这样可以与github上的aliyunpan-cli项目配合实现命令行环境上传下载文件。

有空先
